language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Qv7zxbYMljmQhJJqRihHZ30RXlDZijy/5Tc+nEeyJnyPvADWgB1zEB5T4wFhcUYC5IgctMA62gxWkUz3B4wzEKFtAFdllXZHmbRWTKNKIdLTA3PXpXQn1ZW0GoCj68NhMomctWaz+SEcE7jqR30OsCdaXQeue3PA2ZvnTlrwcF7tZ/0j9VSnqqkadzn7+F5se+rvdNllqAuTgnzZk6C7/FwW9Kc6y+iwDHEC2p5EK7CuouASZ1Oe5rBeY3SFRhTUrkKxW8voQVBPXkl3e+673XMvDapDgM4Ih8hs4Xiy4x/coTSEEUw0t/5uPrV6g3JIcuWI2dkOkebdHO8gebUvLtUoVSJ0ZzYS3W5jo7rNGHobXBbyPLW2hIJ218DveHvRuy336PeT4zEJD8Co1Q28CanbfB8vWjf7iwIYnpbsSBcd5Yb8qfPrPej7WqthbyRu9CEyTTik6VkzWgbxtceFk3aatRy9hkKExOBchl0G2n9N3C7mCnnP4eeoTv9cRczSnePygGeZW3e5J8tfCmD4LqD+rhDbjI3MhDaO7rR0At0+HTwYqrBaGRFgThsUKeC+uj1n3OGnJh5/AwRybDF3fBH+u21+KslkAUyw0mbshFxGYAqhg4UYSK9sobUG47Rxu0Ybsor415S+1zx2V/VMcGFfl/L6Tts88SMpoMOja4Q=
